autoplaylistpoetry/__init__.py
from app import create_app

autoplaylistpoetry/api/__init__.py
from views import api

autoplaylistpoetry/api/views.py
import json
import logging
import re

from flask import Blueprint, request
from autoplaylistpoetry.connections import get_redis_cache

from playlist.generator import PlaylistGenerator, ApiException, spotify_uri_to_url
from playlist.plthreading import generate_multiple_playlists_threaded


api = Blueprint('api', __name__)
logger = logging.getLogger(__name__)


@api.route('/api/playlist', methods=['GET'])
def api_playlist():
    cache = get_redis_cache()
    message = request.args.get('message')
    try:
        if message:
            messages = [sentence for sentence in re.split(r'[.?!/\n]', message) if len(sentence) > 0]
            if len(messages) > 1:
                # If we have multiple messages, process them concurrently
                playlist = []
                incomplete = False
                results = generate_multiple_playlists_threaded(messages, cache)
                for result in results:
                    if result[1]:
                        incomplete = True
                    playlist.extend(result[0])
            else:
                pl_gen = PlaylistGenerator(cache)
                playlist, incomplete = pl_gen.generate_playlist(messages[0])

            if playlist:
                generated_playlist = [{'name': item.name, 'uri': item.uri, 'url': spotify_uri_to_url(item.uri)} for item
                                      in playlist]
                payload = {'success': True, 'partial': incomplete, 'playlist': generated_playlist}
            else:
                payload = {'error': True, 'message': "Not able to generate playlist!"}
        else:
            payload = {'error': True, 'message': "No message provided!"}
    except ApiException as e:
        logger.warn("An error occured with the Spotify API. Statuscode: %s", e.status)
        payload = {'error': True, 'message': "The Spotify API returned an error({})".format(str(e.status))}

    return json.dumps(payload)

autoplaylistpoetry/app.py
import logging.config

from flask import Flask, render_template

from autoplaylistpoetry.web import web
from autoplaylistpoetry.api import api


DEFAULT_BLUEPRINTS = (
    web,
    api
)


def create_app(blueprints=None):
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(__name__)
    config_app(app)
    config_blueprints(app, blueprints)
    config_error_pages(app)
    return app


def config_app(app):
    app.config.from_object('autoplaylistpoetry.config')
    app.config.from_envvar('APP_CONFIG', silent=True)
    logging.config.dictConfig(app.config['LOGGING'])


def config_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def config_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('web/404.html'), 404

autoplaylistpoetry/web/__init__.py
from views import web

autoplaylistpoetry/web/views.py
import logging.config
import os
import re

from flask import Blueprint, send_from_directory, render_template, request

from autoplaylistpoetry.connections import get_redis_cache
from playlist.generator import PlaylistGenerator, spotify_uri_to_url, ApiException
from playlist.plthreading import generate_multiple_playlists_threaded


web = Blueprint('web', __name__)
logger = logging.getLogger(__name__)


@web.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(web.root_path, 'static'), 'ico/favicon.ico')


@web.errorhandler(404)
def page_not_found(e):
    return render_template('web/404.html'), 404


@web.route('/')
def index():
    return render_template('web/index.html')


@web.route('/about')
def about():
    return render_template('web/about.html')


@web.route('/create')
def create():
    return render_template('web/create.html')


@web.route('/generate', methods=['POST'])
def generate():
    cache = get_redis_cache()
    message = request.form['source-text']
    logger.info("Generating playlist from message: %s", message)
    try:
        if message:
            messages = [sentence for sentence in re.split(r'[.?!/\n]', message) if len(sentence) > 0]
            if len(messages) > 1:
                # If we have multiple messages, process them concurrently
                playlist = []
                incomplete = False
                results = generate_multiple_playlists_threaded(messages, cache)
                for result in results:
                    if result[1]:
                        incomplete = True
                    playlist.extend(result[0])
            else:
                pl_gen = PlaylistGenerator(cache)
                playlist, incomplete = pl_gen.generate_playlist(messages[0])

            if playlist:
                heading = "This is your playlist"
                if incomplete:
                    subheading = "Only partial playlist available"
                else:
                    subheading = None
                generated_playlist = [(item.name, item.uri, spotify_uri_to_url(item.uri)) for item in playlist]
            else:
                heading = "Not able to generate playlist!"
                subheading = "Please try another phrase"
                generated_playlist = None
        else:
            heading = "Empty message provided!"
            subheading = "Please try a real phrase"
            generated_playlist = None
    except ApiException as e:
        heading = "Something's wrong with the Spotify API"
        subheading = "Statuscode returned: {}".format(str(e.status))
        logger.warn("An error occured with the Spotify API. Statuscode: %s", e.status)
        generated_playlist = None

    return render_template('web/generate.html', message=message, heading=heading, subheading=subheading,
                           playlist=generated_playlist)

autoplaylistpoetry/templates/web/about.html
{% extends "web/base.html" %}
{% block title %} - About{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>About<small>Auto Playlist Poetry</small></h1>
    </div>
    <p>
    This little (web)app automatically generates <a href="https://www.spotify.com/">Spotify</a> playlists based on a search
    query entered by the user.
    Auto Playlist Poetry is a proof-of-concept that's inspired by <a href="http://playlistpoetry.com/"><strong>Playlist Poetry</strong></a>,
    which in turn was based on <a href="http://spotifypoetry.tumblr.com/">this Tumbler blog</a>.
    The idea is that the user can provide a message and the application will use the Spotify Metadata API to find songs
    whose titles together make up the provided message. Currently it manages to find playlists for single sentences (long or short)
    and multiple small sentences. Anything longer than that will freeze the webapp. Work In Progress.
    </p>
    <p>You can find the source code for this project <a href="https://github.com/DandyDev/autoplaylistpoetry">on GitHub</a> and
    a you can find how it was build <a href="http://dandydev.net/blog/autoplaylistpoetry">here</a></p>
{% endblock %}

autoplaylistpoetry/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="{{ url_for('static', filename='ico/favicon.ico') }}">

        <title>AutoPlaylistPoetry{% block title %}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

        <link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600' rel='stylesheet'>

        <!-- Custom styles for this site -->
        <style>
            body {
                padding-top: 60px;
                padding-bottom: 20px;
                font-size: 16px;
                font-family: "Open Sans", serif;
            }

            h1 {
                font-family: "Abel", Arial, sans-serif;
                font-weight: 400;
                font-size: 40px;
            }

            .margin-base-vertical {
                margin: 40px 0;
            }
        </style>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% endblock %}
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('web.index') }}">AutoPlaylistPoetry</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('web.create') }}">Create</a></li>
                <li><a href="{{ url_for('web.about') }}">About</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    <hr>

    {% block footer %}
        <footer class="footer">
            <p>&copy;2014 Daan Debie</p>
        </footer>
    {% endblock %}

</div>
<!-- /container -->

{% block js_footer %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% endblock %}
</body>
</html>

autoplaylistpoetry/templates/web/create.html
{% extends "web/base.html" %}
{% block title %} - Create{% endblock %}
{% block content %}
    <h1>Create a Spotify playlist</h1>
    <form action="{{ url_for('web.generate') }}" method="post" role="form">
        <div class="form-group">
            <label for="source-text">Your pretty poem</label>
            <textarea name="source-text" id="source-text" rows="3" class="form-control"></textarea>
        </div>
        <span class="help-block">Type the text you want to transform into a playlist.</span>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

autoplaylistpoetry/templates/web/generate.html
{% extends "web/base.html" %}
{% block title %} - Create{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>{{ heading }} {% if subheading %}<small>{{ subheading }}</small>{% endif %}</h1>
    </div>
    <div class="media">
        {% if playlist %}
            {% for item in playlist %}
                <div class="media-body">
                    <h4 class="media-heading">{{ item[0] }}</h4>
                    <a target="_blank" href="{{ item[2] }}">Link to spotify</a>
                <div class="media">
                    <div class="media-body">
                        <iframe src="https://embed.spotify.com/?uri={{ item[1] }}" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>
                    </div>
                </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <p>
        <small>You searched for: '{{ message }}'</small>
    </p>
    <a href="{{ url_for('web.create') }}" class="btn btn-primary" type="button">Try again</a>
{% endblock %}

autoplaylistpoetry/templates/web/index.html
{% extends "web/base.html" %}
{% block title %} - Home{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1>Auto Playlist Poetry</h1>

        <p>Create Spotify playlists from any text!</p>

        <p><a href="{{ url_for('web.create') }}" class="btn btn-primary btn-lg" role="button">Let's go! &raquo;</a></p>

    </div>
{% endblock %}